### ISSUE TITLE
logfile is still named `addressbook`

### ISSUE THREAD

**Issue by jontmy** [jontmy/pe#10]
logfile is still named `addressbook`, but the JSON file has the correct name, which seems inconsistent:

![Screenshot 2022-11-11 at 17.07.40.png](https://raw.githubusercontent.com/jontmy/pe/master/files/bc8626cf-82e6-40ed-8501-4dfc5284e41e.png)

**Comment by nus-se-script** [comment]
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
Naming of the logfile is not a functionality. Different naming of the logfile is not considered as a bug too.

# Items for the Tester to Verify

## :question: Issue response

Team chose [`response.Rejected`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------
