### ISSUE TITLE
add_tut: adding a date on a non-leap year for 29 Feb gets silently added as 28 Feb

### ISSUE THREAD

**Issue by jontmy** [jontmy/pe#9]
### Steps to Reproduce

```
addtut g/T08 c/UML diagrams t/2022-02-29 1400
```

### Expected Behavior
Should reject the date as there isn't a 29 Feb on a non-leap year 2022.

### Actual Behavior
Silently adds the tut with 28 Feb instead.

### Screenshots

![Screenshot 2022-11-11 at 17.05.05.png](https://raw.githubusercontent.com/jontmy/pe/master/files/efb601ab-6082-4c73-9bc0-e09a5867f14b.png)

**Comment by nus-pe-script** [comment]
[IMPORTANT!: Please do not edit or reply to this comment using the GitHub UI. You can respond to it using CATcher during the next phase of the PE]

# Team's Response
We are aware that it is a flaw in the feature, however, we have mentioned it the UG that 29 Feb input will lead to an output of 28 Feb
![image.png](https://raw.githubusercontent.com/nus-cs2103-AY2223S1/pe/master/files/42639efa-8f30-4716-b920-c2d1270c8a6a.png)

# Items for the Tester to Verify

## :question: Issue response

Team chose [`response.NotInScope`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------

## :question: Issue severity

Team chose [`severity.Low`]
Originally [`severity.Medium`]

- [ ] I disagree

**Reason for disagreement:** [replace this with your reason]

-------------------
